import {
    HiChartPie,
    HiUser,
    HiCollection,
    HiAdjustments,
    HiPlusCircle,
    HiCurrencyDollar,
    HiCash,
    HiClipboardList,
    HiHashtag,
    HiUsers,
    HiUserGroup,
    HiUserCircle,
    HiOutlineTruck,
    HiDatabase,
    HiShoppingBag,
    HiReceiptTax,
    HiHome,
    HiInboxIn,
    HiOutlineCash,
    HiOutlineTable
} from "react-icons/hi";

export default [
    {
        name: "Dashboard",
        show: true,
        icon: HiChartPie,
        route: route("dashboard"),
        active: "dashboard",
        permission: "view-dashboard",
    },
    {
        name: "Fastboat",
        show: true,
        icon: HiCollection,
        items: [
            {
                name: "Dock",
                show: true,
                icon: HiClipboardList,
                route: route("fastboat.place.index"),
                active: "fastboat.place.*",
                permission: "view-fastboat-place",
            },
            {
                name: "Track",
                show: true,
                icon: HiClipboardList,
                route: route("in.dev"),
                active: "fastboat.track.*",
                permission: "view-fastboat-track",
            },
            {
                name: "Order",
                show: true,
                icon: HiClipboardList,
                route: route("in.dev"),
                active: "fastboat.order.*",
                permission: "view-fastboat-order",
            },
        ],
    },
    {
        name: "Customer",
        show: true,
        icon: HiCollection,
        route: route("in.dev"),
        active: "customers.index",
        permission: "view-customer",
    },
    {
        name: "Setting",
        show: true,
        icon: HiCollection,
        items: [
            {
                name: "General",
                show: true,
                icon: HiPlusCircle,
                route: route("setting.general"),
                active: "setting.general",
                permission: "view-setting",
            },
            {
                name: "Payment",
                show: true,
                icon: HiClipboardList,
                route: route("setting.payment"),
                active: "setting.payment",
                permission: "view-setting",
            },
        ],
    },
    {
        name: "User",
        show: true,
        icon: HiUser,
        items: [
            {
                name: "Roles",
                show: true,
                icon: HiUserGroup,
                route: route("roles.index"),
                active: "roles.*",
                permission: "view-role",
            },
            {
                name: "Users",
                show: true,
                icon: HiUsers,
                route: route("user.index"),
                active: "user.index",
                permission: "view-user",
            },
        ],
    },
];
