import {
    HiChartPie,
    HiUser,
    HiOutlineNewspaper,
    HiViewGrid,
    HiClipboardList,
    HiUsers,
    HiUserGroup,
    HiUserCircle,
    HiOutlineTruck,
    HiTemplate,
    HiOutlineCash,
    HiPaperAirplane,
    HiOutlineCog,
    HiCash,
    HiOutlineCube,
} from "react-icons/hi";

export default [
    {
        name: "Dashboard",
        show: true,
        icon: HiChartPie,
        route: route("dashboard"),
        active: "dashboard",
        permission: "view-dashboard",
    },
    {
        name: "Fastboat",
        show: true,
        icon: HiPaperAirplane,
        items: [
            {
                name: "Dock",
                show: true,
                icon: HiClipboardList,
                route: route("fastboat.place.index"),
                active: "fastboat.place.*",
                permission: "view-fastboat-place",
            },
            {
                name: "Track",
                show: true,
                icon: HiClipboardList,
                route: route("fastboat.track.index"),
                active: "fastboat.track.*",
                permission: "view-fastboat-track",
            },
        ],
    },
    {
        name: "Tour Packages",
        show: true,
        icon: HiOutlineCube,
        route: route("in.dev"),
        active: "tour-package.index",
        permission: "view-customer",
    },
    {
        name: "Car Rentals",
        show: true,
        icon: HiOutlineTruck,
        route: route("in.dev"),
        active: "car-rental.indedx",
        permission: "view-customer",
    },
    {
        name: "Customer",
        show: true,
        icon: HiUserCircle,
        route: route("customer.index"),
        active: "customer.index",
        permission: "view-customer",
    },
    {
        name: "Order",
        show: true,
        icon: HiOutlineCash,
        route: route("in.dev"),
        active: "order.index",
        permission: "view-order",
    },
    {
        name: "Blog",
        show: true,
        icon: HiOutlineNewspaper,
        items: [
            {
                name: "Posts",
                show: true,
                icon: HiClipboardList,
                route: route("post.index"),
                active: "post.index",
                permission: "view-post",
            },
            {
                name: "Tags",
                show: true,
                icon: HiClipboardList,
                route: route("tag.index"),
                active: "tag.index",
                permission: "view-tag",
            },
        ],
    },
    {
        name: "Page",
        show: true,
        icon: HiTemplate,
        items: [
            {
                name: "About Us",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
            {
                name: "Terms of service",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
            {
                name: "Privacy Policy",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
            {
                name: "Cookie Policy",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
            {
                name: "Refund Policy",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
            {
                name: "Disclaimer",
                show: true,
                icon: HiTemplate,
                route: route("in.dev"),
                active: "#",
                permission: "view-page",
            },
        ],
    },
    {
        name: "Gallery",
        show: true,
        icon: HiViewGrid,
        route: route("in.dev"),
        active: "order.index",
        permission: "view-gallery",
    },
    {
        name: "Setting",
        show: true,
        icon: HiOutlineCog,
        items: [
            {
                name: "General",
                show: true,
                icon: HiOutlineCog,
                route: route("setting.general"),
                active: "setting.general",
                permission: "view-setting",
            },
            {
                name: "Payment",
                show: true,
                icon: HiCash,
                route: route("setting.payment"),
                active: "setting.payment",
                permission: "view-setting",
            },
        ],
    },
    {
        name: "User",
        show: true,
        icon: HiUser,
        items: [
            {
                name: "Roles",
                show: true,
                icon: HiUserGroup,
                route: route("roles.index"),
                active: "roles.*",
                permission: "view-role",
            },
            {
                name: "Users",
                show: true,
                icon: HiUsers,
                route: route("user.index"),
                active: "user.index",
                permission: "view-user",
            },
        ],
    },
];
