<div>
    <x-select
        wire:model="dropoff"
        placeholder="Dropoff"
        :options="$dropoffs"
        :min-items-for-search="5"
        :clearable="true"
        option-label="name"
        option-value="name"
        name="from"
        required="true"
        autocomplate="off"
        right-icon="location-marker"
    />
</div>