<div>
    <x-select
        wire:model="pickup"
        placeholder="Pickup"
        :options="$pickups"
        :min-items-for-search="5"
        :clearable="true"
        option-label="name"
        option-value="name"
        required="true"
        autocomplate="off"
        right-icon="location-marker"
    />
</div>